name: Build docs
trigger:
  branches:
    include:
    - main
    - sandbox
    - dev
    - test-me-*
pr:
  autoCancel: True
  branches:
    include:
    - main
    - sandbox
    - dev

pool: Default
  # vmImage: ubuntu-latest

variables:
- name: "pythonVersion"
  value: "3.10"

jobs:
- job: ${{ format('docs_{0}_{1}', replace(variables.pythonVersion, '.', ''), replace(variables.pytorchVersion, '.', '')) }}
  displayName: ${{ format('Python {0} | Torch {1}', variables.pythonVersion, variables.pytorchVersion) }}

  steps:
  - checkout: self
    submodules: false

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)

  - bash: echo "##vso[task.setvariable variable=PY]$(python -VV)"
    displayName: set version variables

  - bash: |
      source activate $(venv)
      pip install -e .[docs]
    displayName: Install development dependencies

  - bash: |
      make build-docs
    displayName: Build docs

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'docs/_build/'
      artifactName: HtmlReport
    displayName: Publish docs artifact
